---
title: "Lab_Assignment"
author: "Kristen Howard"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.path = "../Output/",
	message = FALSE,
	warning = FALSE
)
```

We will be doing this assignment with {purrr}

### Load Libraries
```{r}
library(tidyverse) # Load libraries
library(here)
library(purrr) 
library(kableExtra)
```

## PURRR - Map()
### Bring In The File

```{r}
HomePath<-here("Week_12", "Data", "homework") # point to the location on the computer of the folder
files_here <- dir(path = HomePath, pattern = ".csv", full.names = TRUE)
files_here # This is looking good. All 4 TP .cvs appeared!
```

### Read In The File
```{r}
data<- files_here %>%
       set_names() %>% # set's the id of each list to the file name
       map_df(read_csv,.id = "filename") # map everything to a dataframe and put the id in a column                                              called filename
data
```


### Calculations
Calculate the mean and standard deviation of both temperature (Temp.C) and light (Intensity.lux)
```{r}
data<- files_here %>% # Load in data
       set_names() %>% # set's the id of each list to the file name
       map_df(read_csv,.id = "filename") %>% # map everything to a dataframe and put the id in a                                                     column called filename
      group_by(filename) %>% # Group by the filenames
      summarise(mean_temp = mean(Temp.C, na.rm = TRUE), # Calculations for mean and sd for both variables
                mean_Ilux = mean(Intensity.lux,na.rm = TRUE),
                sd_temp = sd(Temp.C, na.rm = TRUE),
                sd_Ilux = sd(Intensity.lux, na.rm = TRUE))

# try summarize_at_() or try using last weeks knowledge to extract the TP
```
### Now, let's make this a nicer table
```{r, PURRR_Map_Function}
data %>%
  kbl(caption = "Files and their corresponding average mean and standard deviation") %>%
  kable_classic() %>%
  kable_styling(full_width = F)

```

### For Loops
#### List Files in Directory
```{r}
HomePath<-here("Week_12", "Data", "homework") # Set paths
files <- dir(path = HomePath,pattern = ".csv")
files # We can see all of our files
```

```{r}
TP_data<-data.frame(matrix(nrow = length(files), ncol = 5)) # make an empty dataframe that has one row for each file and 3 columns
colnames(TP_data)<-c("filename","mean_temp", "mean_Ilux", "sd_temp", "sd_Ilux") # Set column names
TP_data # View
```

```{r}
raw_data<-read_csv(paste0(HomePath,"/",files[1])) # test by reading in the first file and see if it works
head(raw_data)
```


```{r}
mean_temp<-mean(raw_data$Temp.C, na.rm = TRUE) # calculate mean
mean_temp
sd_temp<-sd(raw_data$Temp.C, na.rm = TRUE) # calculate sd
sd_temp
mean_Ilux<-mean(raw_data$Temp.C, na.rm = TRUE) # calculate  mean
mean_Ilux
sd_Ilux<-sd(raw_data$Intensity.lux, na.rm = TRUE) # calculate sd
sd_Ilux
```


```{r, ForLoop}
for (i in 1:length(files)){ # loop over 1:4 the number of files


raw_data <- read_csv(paste0(HomePath,"/",files[i])) 
TP_data$filename[i] <- files[i]
TP_data$mean_temp[i] <- mean(raw_data$Temp.C, na.rm = TRUE) # Now add in all the means and standard                                                                  deviations
TP_data$sd_temp[i] <- sd(raw_data$Temp.C, na.rm = TRUE)
TP_data$mean_Ilux[i] <- mean(raw_data$Intensity.lux, na.rm = TRUE)
TP_data$sd_Ilux[i] <- sd(raw_data$Intensity.lux, na.rm = TRUE)
}

TP_data
```


