---
title: "Intro2Rmarkdown2"
author: "Kristen Howard"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: TRUE
  toc_float: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.path = "../Output/",
	message = FALSE,
	warning = FALSE
)
```

# Load Libraries

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(palmerpenguins)
library(kableExtra)
```

# Load Data

```{r}
view(penguins)
summary(penguins)
```

## Including Plots

You can also embed plots, for example:

```{r penguin, echo=FALSE, fig.align='center', fig.asp=1.2, message= FALSE, warning=FALSE, fig.cap="This is the best penguin figure ever"}
penguins %>%
  ggplot(mapping = aes(x = body_mass_g, 
                       y = bill_depth_mm,
                       color = species)) +
  geom_point() +
  geom_smooth(method = "lm")
  labs(x = "Bird Mass (g)", y = "Bill Depth (mm)")
  theme_bw()
```

# Creating a Table

We will be creating a table in R markdown This does not get its own code chunk

| Time   | Session  |     Topic |
|:-------|:--------:|----------:|
| *left* | *center* | **right** |
| 01:00  |    1     |   Anatomy |
| 01:50  |          |   *Break* |
| 02:00  |    2     |    Tables |
| 02:45  |          |   *Break* |

# Now Let's Create a Table with kable

```{r}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl()%>% # make it a kable table 
  kable_classic() %>%
  row_spec(2, bold = T, color = "pink", background = "green") %>%
  kable_styling(full_width = FALSE)

```

S
